name: test
channels:
  - conda-forge
  - default
dependencies:
  - click
  - conda-vendor
  - conda=4.12.0
  - mamba
  - micromamba  
  - conda-lock=1.*
  - conda-build  
  - jinja2
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - python
  - requests
  - ruamel.yaml
  - urllib3
