# name: wif-ci
# on:
#   push:
#     branches:
#     - 'main'

# jobs:
#   build:
#     name: "Test WIF"
#     runs-on: ubuntu-latest
#     timeout-minutes: 90
#     permissions:
#       contents: 'read'
#       id-token: 'write'
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - id: auth
#         uses: google-github-actions/auth@v0.4.0
#         with:
#           token_format: "access_token"
#           create_credentials_file: true
#           activate_credentials_file: true
#           workload_identity_provider: 'projects/918030991691/locations/global/workloadIdentityPools/github-wif-pool-eae/providers/githubwifeae'
#           service_account: ${{ secrets.SERVICE_ACCOUNT }}
#           access_token_lifetime: '110s'
#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v0.3.0
#       - name: set crdential_file
#         run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}
#       - name: Run gcloud
#         run: gcloud compute instances list --zones us-central1