# {
#   "name": "qhub auto update",
#   "on": {
#     "push": {
#       "branches": [
#         "main"
#       ],
#       "paths": [
#         "qhub-config.yaml"
#       ]
#     }
#   },
#   # "env": {
#   #   "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
#   #   "AWS_ACCESS_KEY_ID": "${{ secrets.AWS_ACCESS_KEY_ID }}",
#   #   "AWS_SECRET_ACCESS_KEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
#   #   "SPACES_ACCESS_KEY_ID": "${{ secrets.SPACES_ACCESS_KEY_ID }}",
#   #   "SPACES_SECRET_ACCESS_KEY": "${{ secrets.SPACES_SECRET_ACCESS_KEY }}",
#   #   "DIGITALOCEAN_TOKEN": "${{ secrets.DIGITALOCEAN_TOKEN }}"
#   # },
#   "jobs": {
#     "build": {
#       "name": "qhub",
#       "runs-on": "ubuntu-latest",
#       "steps": [
#         {
#           "name": "Checkout Image",
#           "uses": "actions/checkout@master",
#           "with": {
#             "token": "${{ secrets.REPOSITORY_ACCESS_TOKEN }}"
#           }
#         },
#         {
#           "name": "Set up Python",
#           "uses": "actions/setup-python@v2",
#           "with": {
#             "python-version": "3.8"
#           }
#         },
#         {
#           "name": "Install QHub",
#           "run": "pip install git+https://github.com/Quansight/qhub.git@main"
#         },
#         # {
#         #   "name": "Deploy Changes made in qhub-config.yaml",
#         #   "run": "qhub deploy -c qhub-config.yaml --disable-prompt --skip-remote-state-provision"
#         # },
#         {
#           "name": "Push Changes",
#           "run": "echo ${{ env.COMMIT_MSG }}",
#           "env": {
#             "COMMIT_MSG": "qhub-config.yaml automated commit: ${{ github.sha }}"
#           }
#         }
#       ]
#     }
#   }
# }