name: play with it

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GCP auth
        id: gcpauth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}
          
      - name: Use gcloud CLI
        run: gcloud info

      - name: List k8s clusters
        shell: bash
        run: |
          gcloud container clusters list
          gsutil list -p $PROJECT_ID