name: play with it

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:
    inputs:
          branch:
            description: 'test env var'
            required: true
            default: 'main'
            type: string
env:
  CLOUD_PROVIDER: gcp
  QHUB_GH_BRANCH: ${{ github.event.inputs.branch || 'main'}}
  QHUB_DOMAIN: eaetest.qhub.dev
  QHUB_PROJECT_NAME: eaetest


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo shit
      run: |
        echo $QHUB_GH_BRANCH

      # - name: GCP auth
      #   id: gcpauth
      #   uses: google-github-actions/auth@v0.4.0
      #   with:
      #     credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v0.3.0
      #   with:
      #     project_id: ${{ secrets.PROJECT_ID }}
      #     service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
      #     export_default_credentials: true

      # - name: Use gcloud CLI
      #   run: gcloud info

      # - name: List k8s clusters
      #   shell: bash
      #   run: |
      #     gcloud container clusters list
      #     gsutil ls
          
      # - name: Install QHub
      #   shell: bash
      #   run: |
      #     git clone https://git@github.com/quansight/qhub.git
      #     cd qhub
      #     git fetch origin $QHUB_GH_BRANCH
      #     git checkout $QHUB_GH_BRANCH
      #     pip install .
      #     pwd

      # - name: Init QHub
      #   shell: bash
      #   run: |
      #     mkdir qhub-new
      #     cd qhub-new
      #     qhub init $CLOUD_PROVIDER \
      #     --domain $QHUB_DOMAIN \
      #     --project $QHUB_PROJECT_NAME \
      #     --auth-provider password \
      #     --disable-prompt
      #     echo "*** qhub-config.yaml *** "
      #     cat "qhub-config.yaml"
