name: Test Micromamba

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  micromamba:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          cache-env: true
          environment-file: environment.yml
          environment-name: test
          channels: conda-forge
          channel-priority: strict
      
      - name: Which micromamba
        run: which micromamba

      - name: conda-vendor vendor
        run: conda-vendor vendor --file environment-test.yml --solver micromamba --platform linux-64

      - name: create local channel env
        run: micromamba create --file environment-test-local-channel.yml --offline

      - name: micromamba env list
        run: micromamba env list
