name: Test Micromamba

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  micromamba:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          cache-env: true
          environment-file: environment.yml
          environment-name: test
          channels: conda-forge
          channel-priority: strict
      
      - name: Which micromamba
        run: which micromamba

      - name: micromamba env list
        run: micromamba env list

      - name: create new env
        run: micromamba create --file environment-test.yml
