# name: tmate

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 15

    - name: get event details
      run: |
        echo "${{ toJson(github) }}"
        echo "${{ toJson(github.event.pull_request.head.repo.full_name) }}"
        echo "${{ toJson(github.event.pull_request.base.repo.full_name) }}"
      # echo "FULL_NAME=$(github.event.pull_request.head.repo.full_name)" >> $GITHUB_ENV

    - name: test
      if: github.event_name == "pull_request" && github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name
      run: |
        echo "YELLO WORLD!"
